### ISSUE TITLE
Error while parsing unicode characters

### ISSUE THREAD

**Issue by lewis-munyi** [itzmeanjan/chanalyze#6] opened 2020-06-28 18:02 UTC
The program throws an error when it tries to parse Unicode characters as shown below. 
![image](https://user-images.githubusercontent.com/15906323/85954757-6505fe00-b982-11ea-9a7c-cf68213c7348.png)

**Comment by itzmeanjan** [comment] 2020-06-29 02:16
Thanks @lewis-munyi for reporting :+1: 

I'm taking a look at it.

**Comment by itzmeanjan** [comment] 2020-06-29 02:30
Hello @lewis-munyi ,

I've added a fix to this error, _by putting error handling in case of decoding failure_. 
New version **( v0.3.6 )** can be downloaded from PyPI. 

Thanks :)

**Comment by lewis-munyi** [comment] 2020-06-29 05:39
Hi @itzmeanjan 
The error handling fixed displaying the error but it's still there. 

I thought maybe I could check it out myself but this happened. :(
![image](https://user-images.githubusercontent.com/15906323/85976829-070a0280-b9e4-11ea-8f5c-fe6437d3b1e3.png)

**Comment by itzmeanjan** [comment] 2020-06-29 08:52
Hey @lewis-munyi ,

Looks like you're on windows and file name I used isn't supported on windows. I'll fix that, which is why you can't clone repo. 

And for the error in script, I'd request you to dig in, because it's caused by some data, which I don't have access to. I can't reproduce it .

**Comment by itzmeanjan** [comment] 2020-06-29 17:48
Hello @lewis-munyi ,

please check latest commit on `master`, I've fixed `invalid path` issue on windows !

**Comment by itzmeanjan** [comment] 2020-07-02 15:49
I've fixed issues from my side, also released new version v0.3.7.

As of now I'm closing this issue, please open a new one, if required. 

Thanks :)

**Closed as completed by itzmeanjan** 2020-07-02 15:49 UTC
